/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{
        type: 'autogenerated',
        dirName: '.'
    }, {
        type: 'category',
        label: 'External resources',
        collapsible: false,
        items: [{
            type: 'link', label: 'GATENet Website', href: 'https://gatenet.io'
        },{
            type: 'link', label: 'GATENet Staking Platform', href: 'https://staking.gatenet.io'
        }, {
            type: 'link', label: 'GATENet GitHub', href: 'https://github.com/gateNet-IO/'
        }]
    }],
};
